# Generated by Django 3.2 on 2021-04-27 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('msgservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgservice',
            name='email_id',
            field=models.EmailField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
