# Generated by Django 3.2 on 2021-04-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_alter_exam_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={},
        ),
    ]
