# Generated by Django 3.2 on 2021-04-27 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_alter_exam_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
