# Generated by Django 3.2 on 2021-04-27 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_exam_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='image',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
